apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-deployment
spec:
  replicas: 1
  serviceAccountName: kubesa
  selector:
    matchLabels:
      app: apache-app
  template:
    metadata:
      labels:
        app: apache-app
    spec:
      containers:
      - name: kube-apache
        image: kubeorg.azurecr.io/jeevas008/codedeploy:#{Build.BuildId}#
        ports:
        - containerPort: 5000
# service type loadbalancer       
---
apiVersion: v1
kind: Service
metadata:
  name: kube-deployment-svc
spec:
  serviceAccountName: kubesa
  selector:
    app: apache-app-svc
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: LoadBalancer
