trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: Docker@2
    displayName: 'Build and Push Docker Image'
    inputs:
      containerRegistry: 'jeevaconreg'  # Replace with your Azure Container Registry connection name
      repository: 'azureapp'
      command: 'buildAndPush'
      Dockerfile: '.'
      buildContext: '$(Build.SourcesDirectory)'
      tags: |
        $(Build.BuildId)
        latest
