trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: Docker@2
    displayName: 'Build Docker image'
    inputs:
      containerRegistry: 'jeevaconreg.azurecr.io'  # Replace with your Azure Container Registry connection name
      repository: 'codedeploy'
      command: 'build'
      Dockerfile: '.'
      buildContext: '$(Build.SourcesDirectory)'
      tags: |
        $(Build.BuildId)
        latest
